export const RESET_DEFAULT = 'RESET_DEFAULT';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_FAILURE = 'SEARCH_PRODUCT_FAILURE';
export const ADD_LAST_SEARCH = 'ADD_LAST_SEARCH';
