export const palettes = {
  default: {
    primary: '#007AFF',
    background: '#FEFBF7',
    card: '#FFFFFF',
    text: '#0A0A0A',
    border: '#EAEAEA',
    notification: '#FF453A',
    white: '#FFFFFF',
    grey: '#8C8C8C',
    red: '#FF0F0F',
    modal: '#0000005A',
    black: '#0A0A0A',
  },
  dark: {
    primary: '#0A84FF',
    background: '#202020',
    card: '#1C1C1C',
    text: '#F5F5F5',
    border: '#EAEAEA',
    notification: '#FF453A',
    white: '#FFFFFF',
    grey: '#8C8C8C',
    red: '#FF0F0F',
    modal: '#FEFBF75A',
    black: '#0A0A0A',
  },
};
