import {StyleSheet} from 'react-native';

export const useStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    header: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      backgroundColor: 'transparent',
      overflow: 'hidden',
    },
    headerContent: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 16,
      alignItems: 'center',
    },
    backgroundImage: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      width: '100%',
      height: '100%',
      resizeMode: 'stretch',
    },
    contentContainer: {
      // Add padding or margin as needed
      marginTop: '70%',
      paddingHorizontal: 16,
      paddingBottom: 20,
    },
    textTitle: {
      fontSize: 18,
      fontWeight: '600',
      lineHeight: 32,
      letterSpacing: 0.8,
      marginTop: 22,
      color: colors.text,
      textTransform: 'capitalize',
    },
    label: {
      fontSize: 16,
      color: colors.text,
      fontWeight: '600',
      lineHeight: 19.2,
      letterSpacing: 0.8,
    },
    imgThumbnail: {
      height: 80,
      width: 80,
      resizeMode: 'contain',
      marginRight: 4,
    },
    imgThumbnailSel: {
      height: 80,
      width: 80,
      resizeMode: 'contain',
      marginRight: 4,
      borderWidth: 1,
      borderColor: '#00FF00',
    },
    mapImgThumbnail: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    textDescription: {
      fontSize: 14,
      lineHeight: 18.6,
      letterSpacing: 0.5,
      textAlign: 'justify',
      marginTop: 10,
      color: colors.grey,
    },
    priceWrapper: {
      marginTop: 12,
      marginBottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '49%',
    },
    priceWrapperSimilar: {
      marginTop: 12,
      marginBottom: 12,
      flexDirection: 'row',
      // flexWrap: 'wrap',
    },
    textPrice: {
      fontSize: 24,
      color: colors.text,
      fontWeight: '600',
      lineHeight: 26,
      letterSpacing: 0.5,
    },
    textPriceSimilar: {
      fontSize: 16,
      color: colors.text,
      fontWeight: '800',
      lineHeight: 16.8,
      letterSpacing: 0.5,
    },
    textPriceDisc: {
      fontSize: 12,
      fontWeight: '400',
      letterSpacing: 0.5,
      lineHeight: 14.4,
      color: colors.grey,
      textDecorationLine: 'line-through',
    },
    textDisc: {
      fontSize: 14,
      fontWeight: '500',
      letterSpacing: 0.5,
      lineHeight: 15.6,
      color: colors.red,
    },
    spacer: {
      height: 8,
      backgroundColor: '#EFEFEF',
    },
    detailWrapper: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 20,
    },
    cardDetail: {
      marginTop: 16,
    },
    detailInfo: {
      marginTop: 10,
      marginBottom: 10,
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: '#EAEAEA',
      paddingBottom: 20,
    },
    textDetailInfoLabel: {
      flex: 1,
      fontSize: 14,
      lineHeight: 15.6,
      color: colors.grey,
      letterSpacing: 0.5,
    },
    textDetailInfoValue: {
      flex: 1,
      fontSize: 14,
      color: colors.text,
      lineHeight: 15.6,
      letterSpacing: 1,
    },
    marTop10: {
      marginTop: 10,
    },
    cardSimilar: {
      marginRight: 12,
      width: 140,
      borderWidth: 1,
      borderRadius: 6,
      paddingBottom: 5,
    },
    similarImg: {
      height: 100,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      resizeMode: 'stretch',
    },
    contentSimilar: {
      padding: 5,
      flexGrow: 1,
      flexShrink: 1,
    },
    textTitleSimilar: {
      fontSize: 14,
      fontWeight: '400',
      lineHeight: 19.2,
      letterSpacing: 0.5,
      marginTop: 4,
    },
    ratingWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    textRating: {
      fontSize: 16,
      fontWeight: '500',
      letterSpacing: 0.5,
      lineHeight: 18.6,
    },
    textRatingSimilar: {
      fontSize: 12,
      fontWeight: '400',
      letterSpacing: 0.5,
      lineHeight: 18.6,
    },
    discWrapper: {
      position: 'absolute',
      top: 6,
      left: 4,
      backgroundColor: colors.red,
      borderRadius: 6,
      padding: 2,
    },
    discText: {
      color: colors.white,
      fontSize: 11,
      lineHeight: 13,
      letterSpacing: 0.5,
      textAlign: 'center',
    },
  });
